name: sync_translations
description: A sample command-line application.
version: 1.0.2
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  sync_translations: sync_translations
# To Activate this application, run:
# dart pub global activate --source path .
# To Deactivate this application, run:
# dart pub global deactivate sync_translations
# To run this application, run:
# sync_translations
