name: sync_translations
description: >
  A Dart CLI tool that synchronizes translation files across multiple locales
  by ensuring all keys are consistent and complete between source and target files.

version: 1.0.3

repository: https://github.com/ma7moud3osman/sync_translations
homepage: https://github.com/ma7moud3osman/sync_translations
issue_tracker: https://github.com/ma7moud3osman/sync_translations/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

topics:
  - localization
  - translations
  - cli
  - dart
  - automation

dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  sync_translations: sync_translations
# To Activate this application globally:
# dart pub global activate sync_translations
#
# To run the command:
# sync_translations
#
# To deactivate:
# dart pub global deactivate sync_translations
